### ISSUE TITLE
Transforming results for a query Result with a page block with multiple tags in properties causes an exception

### ISSUE THREAD

**Issue by Verneri** [cldwalker/logseq-query#2]
For some reason properties with multiple values are kept in a list. This causes an exception when using result transformation presumably due to the `eval` on the line 150 of datascript.cljs

**Comment by MagePrometheus** [comment]
npm 8.19.2 logseq 0.8.7
I don't know whether lq ran the same with previous versions of logseq. With -t sometimes id is the only column displayed. lq sq ... always raises exception.
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
Cm [Error]: ' is not ISeqable

**Comment by cldwalker** [comment]
@Verneri I recall that being an issue with `:block/properties-order` which is why it's filtered out. Could you provide an example query and output that's causing this? This most likely needs to be fixed upstream in logseq. I thought we had fixed all :block attributes returning lists

**Comment by cldwalker** [comment]
@MagePrometheus Sounds like a separate issue and would recommend opening a separate one. I'll need specific steps on what you're typing and what you're seeing to help answer your issue
