### ISSUE TITLE
Extract page name from block

### ISSUE THREAD

**Issue by johngarg** [cldwalker/logseq-query#7]
Hi,

I would like to extract the title of a page from the :block/page id, is this possible?

Thanks

**Comment by cldwalker** [comment]
Hi. Yep. You can by drilling into the :block/page attribute using [a map in a pull](https://docs.datomic.com/pro/query/pull.html#map-specification-example). For example, to pull every block in your graph with its page name: `lq sq '[:find (pull ?b [:block/content :block/name {:block/page [:block/original-name]}]) :where [?b :block/content]]'`

**Comment by johngarg** [comment]
Hi,

Thanks very much for your quick response, this is exactly what I was looking for.
